config/routes.rb
Rails.application.routes.draw do
  # get 'users/profile'
  # resources :users, only: %i[show new create destroy]
  root to: 'pages#home'
  devise_for :users
  get '/profile', to: 'users#profile', as: 'profile'
  get '/users/:id', to: 'users#show', as: 'user'
  resources :consoles do
    resources :rentals
    get '/rentals/:id/confirm', to: 'rentals#confirm', as: 'confirm_rental'
    get '/rentals/:id/approve', to: 'rentals#approve', as: 'approve_rental'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/console.rb
class Console < ApplicationRecord
  belongs_to :user
  has_many :rentals
  has_one_attached :photo

  validates :name, :description, :price_per_day, :min_rental_time, :max_rental_time, presence: true
  validates :name, length: { minimum: 3 }
  validates :description, length: { minimum: 10, maximum: 255 }

  include PgSearch::Model
  pg_search_scope :search_by_name,
                  against: :name,
                  using: :trigram
                  # using: {
                  #   tsearch: { prefix: true }
                  # }
end

app/controllers/consoles_controller.rb
class ConsolesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :user_list
  before_action :console_list, only: %i[show edit update destroy]


  def index
    if params[:query].present?
      @consoles = Console.search_by_name(params[:query])
    else
      @consoles = Console.all
    end
  end

  def show
    @rental = @console.rentals[0]
  end

  def new
    @console = Console.new
  end

  def create
    @console = Console.new(console_params)
    @console.user = current_user
    if @console.save
      redirect_to @console, notice: 'Console was succesfullly created 👍'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @console.update(console_params)
      redirect_to @console, notice: 'Console was successfully updated 👍'
    else
      render :new
    end
  end

  def destroy
    if @console.destroy
      redirect_to profile_path, notice: 'Console was successfully deleted 👍'
    else
      redirect_to profile_path, alert: "Cannot delete a console while it's rented"
    end
  end

  private

  def user_list
    @user = current_user
  end

  def console_list
    @console = Console.find(params[:id])
  end

  def console_params
    params.require(:console).permit(:name, :price_per_day, :min_rental_time, :max_rental_time, :description, :photo)
  end
end

app/views/consoles/edit.html.erb
<div class="container">
  <div class="nes-container">
    <h1>Edit console:</h1>
    <%= simple_form_for @console do |f| %>
      <%= f.input :name, input_html: { class: "nes-input" } %>
      <%= f.input :price_per_day, input_html: { class: "nes-input" } %>
      <%= f.input :min_rental_time, input_html: { class: "nes-input" } %>
      <%= f.input :max_rental_time, input_html: { class: "nes-input" } %>
      <%= f.input :description, input_html: { class: "nes-textarea" } %>
      <%= f.input :photo, as: :file %>
      <%= f.submit class: "nes-btn is-primary" %>
      <%= link_to 'Delete', console_path, class: "nes-btn is-error",
                                          method: :delete,
                                          data: { confirm: "Are you sure?" } %>
      <%= link_to 'Back', :back, class: "nes-btn is-secondary" %>
    <% end %>
  </div>
</div>

app/views/consoles/index.html.erb
<h1 class="text-center">Consoles for rent</h1>

<div class="container">
  <div class="cards">
    <% @consoles.each do |console| %>
      <% if !user_signed_in? || console.user_id != current_user.id %>
        <div class="card-trip">
          <%= link_to console_path(console) do %>
            <% if console.photo.attached? %>
              <%= cl_image_tag console.photo.key, style:'object-fit:cover;'%>
            <% else %>
              <img src="https://res.cloudinary.com/xanldn89/image/upload/v1629884209/stock_console_lktnhq.jpg" />
            <% end %>
          <% end %>
          <div class="card-trip-infos">
            <div class="card-name-and-info-text">
              <h2><%= link_to console.name, console_path(console) %></h2>
              <p><%= console.description %></p>
            </div>
            <h2 class="card-trip-pricing">£<%= console.price_per_day %> per day</h2>
            <% if console.user.photo.attached? %>
              <%= cl_image_tag console.user.photo.key, class:'card-trip-user avatar-bordered' %>
            <% else %>
              <img
                src="https://res.cloudinary.com/xanldn89/image/upload/c_thumb,w_200,g_face/v1630064327/stock_8_bit_hspodr.jpg"
                alt="..." width="130" class="card-trip-user avatar-bordered">
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/consoles/new.html.erb
<div class="container">
  <div class="nes-container">
    <h1>Add console:</h1>
    <%= simple_form_for @console do |f| %>
      <%= f.input :name, input_html: { class: "nes-input" } %>
      <%= f.input :price_per_day, input_html: { class: "nes-input" } %>
      <%= f.input :min_rental_time, input_html: { class: "nes-input" } %>
      <%= f.input :max_rental_time, input_html: { class: "nes-input" } %>
      <%= f.input :description, input_html: { class: "nes-textarea" } %>
      <%= f.input :photo, as: :file %>
      <%= f.submit class: "nes-btn is-primary" %>
      <%= link_to 'Back', :back, class: "nes-btn is-secondary" %>
    <% end %>
  </div>
</div>

app/views/consoles/show.html.erb
<% if @console.photo.attached? %>
  <div class="banner", style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @console.photo.key %>');height:calc(100vh - 64px);">
<% else %>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://res.cloudinary.com/xanldn89/image/upload/v1629884209/stock_console_lktnhq.jpg');height:calc(100vh - 64px);">
<% end %>
    <div class="container">
      <h1><%= @console.name %></h1>
      <p> Price per day: £<%= @console.price_per_day %> <br> Minimum rental time: <%= @console.min_rental_time %> days <br>Maximum rental time: <%= @console.max_rental_time %> days</p>
      <%# <%= link_to "Login", new_user_session_path, class: "btn btn-primary" %>
      <% if @rental %>
        <%= link_to "Rent", "#", class: "nes-btn is-disabled" %>
      <% elsif current_user && @console.user.id == current_user.id %>
        <%= link_to "Edit", edit_console_path, class: "nes-btn is-warning" %>
      <% else %>
        <%= link_to "Rent", new_console_rental_path(console_id: @console), class: "nes-btn is-primary" %>
      <% end %>
      <%= link_to 'Back', :back, class: "nes-btn is-secondary" %>
      <p class="mt-3"><%= @console.description %></p>
    </div>

    <div class="container">
      <% if current_user && @console.user.id == current_user.id %>
        <%= link_to profile_path, class: "nes-badge" do %>
          <span class="is-primary">Owned by you</span>
        <% end %>
      <% else %>
        <%= link_to user_path(@console.user), class: "nes-badge" do %>
          <span class="is-primary">Owned by <%= @console.user.first_name %></span>
        <% end %>
      <% end %>
    </div>

    <% if @rental %>
      <div class="container">
        <%= link_to console_rental_path(@console, @rental), class: "nes-badge" do %>
          <% if @rental.approved? == false %>
            <span class="is-warning">Awaiting Confirmation</span>
          <% else %>
            <% if @rental.current_renter_id == current_user.id %>
              <span class="is-error">Rented by you</span>
            <% else %>
              <span class="is-error">Currently rented</span>
            <% end %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>

<%# <h2>Current</h2> %>

<%# <div class="container"> %>
  <%# <div class="nes-container"> %>

  <%# </div> %>
<%# </div> %>