config/routes.rb
Rails.application.routes.draw do
  # get 'users/profile'
  # resources :users, only: %i[show new create destroy]
  root to: 'pages#home'
  devise_for :users
  get '/profile', to: 'users#profile', as: 'profile'
  get '/users/:id', to: 'users#show', as: 'user'
  resources :consoles do
    resources :rentals
    get '/rentals/:id/confirm', to: 'rentals#confirm', as: 'confirm_rental'
    get '/rentals/:id/approve', to: 'rentals#approve', as: 'approve_rental'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, :last_name, :address, presence: true
  validates :about, length: { maximum: 255 }
  validates :first_name, :last_name, format: { with: /\A([a-z]+[ \-.,']*)+\z/i,
                                               message: "Please use only letters from the latin alphabet, spaces, and punctuation: -.,'" }
  validates :phone_number, format: { with: %r{\A\(?\+?(\d+[ .\-/()]*)+\z},
                                     message: "Please use only numbers 0-9 and punctuation: +.-/()" }
  has_many :consoles, dependent: :destroy
  has_many :rentals, through: :consoles
  has_one_attached :photo
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

module Users
  class ConfirmationsController < Devise::ConfirmationsController
    # GET /resource/confirmation/new
    # def new
    #   super
    # end

    # POST /resource/confirmation
    # def create
    #   super
    # end

    # GET /resource/confirmation?confirmation_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after resending confirmation instructions.
    # def after_resending_confirmation_instructions_path_for(resource_name)
    #   super(resource_name)
    # end

    # The path used after confirmation.
    # def after_confirmation_path_for(resource_name, resource)
    #   super(resource_name, resource)
    # end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    # You should configure your model like this:
    # devise :omniauthable, omniauth_providers: [:twitter]

    # You should also create an action method in this controller like this:
    # def twitter
    # end

    # More info at:
    # https://github.com/heartcombo/devise#omniauth

    # GET|POST /resource/auth/twitter
    # def passthru
    #   super
    # end

    # GET|POST /users/auth/twitter/callback
    # def failure
    #   super
    # end

    # protected

    # The path used when OmniAuth fails
    # def after_omniauth_failure_path_for(scope)
    #   super(scope)
    # end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

module Users
  class PasswordsController < Devise::PasswordsController
    # GET /resource/password/new
    # def new
    #   super
    # end

    # POST /resource/password
    # def create
    #   super
    # end

    # GET /resource/password/edit?reset_password_token=abcdef
    # def edit
    #   super
    # end

    # PUT /resource/password
    # def update
    #   super
    # end

    # protected

    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end

    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end

    def after_sign_in_path_for(_resource)
      consoles_path
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

module Users
  class UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end

    # POST /resource/unlock
    # def create
    #   super
    # end

    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end

    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    @user = current_user
    @consoles = current_user.consoles
    @rentals = Rental.where(current_renter_id: current_user.id)
    # raise
  end

  def show
    @user = User.find(params[:id])
    redirect_to profile_path if current_user == @user
    @consoles = @user.consoles
  end
end

app/views/users/profile.html.erb
<div class="row py-5 px-4">
  <div class="col-md-8 mx-auto">
    <div class="nes-container overflow-hidden">
      <div class="px-4 pt-0 pb-4 cover">
        <div class="media align-items-end profile-head">
          <div class="profile mr-3">
            <% if @user.photo.attached? %>
              <%= cl_image_tag @user.photo.key, style: 'width: 130px;', class:'rounded mb-2 img-thumbnail' %>
            <% else %>
              <img src="https://res.cloudinary.com/xanldn89/image/upload/c_thumb,w_200,g_face/v1630064327/stock_8_bit_hspodr.jpg" alt="..." width="130"
              class="rounded mb-2 img-thumbnail">
            <% end %>
            <%= link_to 'Edit Profile', edit_user_registration_path, class: "nes-btn is-normal", style: "display: block;" %>
          </div>
          <div class="media-body mb-5 text-white">
            <h4 class="mt-0 mb-0"><%= @user.first_name %></h4>
            <p class="small mb-4"> <i class="fas fa-map-marker-alt mr-2"></i><%= @user.address %></p>
          </div>
        </div>
      </div>
      <div class="bg-light p-4 d-flex justify-content-end text-center">
        <ul class="list-inline mb-0">
          <li class="list-inline-item">
            <%# <%  raise %>
            <h5 class="font-weight-bold mb-0 d-block"><%= @consoles.count %></h5><small class="text-muted"> <i
                class="fas fa-image mr-1"></i>Consoles</small>
          </li>
          <li class="list-inline-item">
            <h5 class="font-weight-bold mb-0 d-block"><%= @rentals.count %> </h5><small class="text-muted"> <i
                class="fas fa-user mr-1"></i>Rentals</small>
          </li>
          <li class="list-inline-item">
            <h5 class="font-weight-bold mb-0 d-block" style="font-size:16px;">
              <%# @user.rating.times do %><% 5.times do %>
              👾
              <% end %>
            </h5><small class="text-muted"> <i class="fas fa-user mr-1"></i>Rating</small>
          </li>
        </ul>
      </div>
      <div class="px-4 py-3">
        <h5 class="mb-0">About</h5>
        <div class="p-4 rounded shadow-sm bg-light">
          <p class="font-italic mb-0"><%= @user.about %></p>
        </div>
      </div>
      <div class="py-4 px-4">
        <div class="d-flex align-items-center justify-content-between mb-3">
          <h5 class="mb-0">My consoles</h5>
          <%= link_to 'Add a console', new_console_path, class: "nes-btn is-success" %><%# <a href="#" class="btn btn-link text-muted">Show all</a> %>
        </div>
        <div class="cards">


          <% if @consoles.empty? %>
            <div>
              <h4>You don't have any consoles to rent ): Add one now!</h4>
            </div>
          <% else %>
            <% @consoles.each do |console| %>
              <div class="card-trip">
                <div class="profile-card-image-edit-button">
                  <%= link_to console_path(console) do %>
                    <% if console.photo.attached? %>
                      <%= cl_image_tag console.photo.key, style:'object-fit:cover;'%>
                    <% else %>
                      <img src="https://res.cloudinary.com/xanldn89/image/upload/v1629884209/stock_console_lktnhq.jpg" />
                    <% end %>
                  <% end %>
                  <%= link_to 'Edit', edit_console_path(console), class: "nes-btn is-warning edit-button", style: 'padding: 8px 4px;' %>
                </div>
                <div class="card-trip-infos">
                  <div class="card-name-and-info-text">
                    <h2><%= link_to console.name, console_path(console) %></h2>
                    <p><%= console.description %></p>
                  </div>
                  <% if console.rentals[0] %>
                    <div class="card-badge">
                      <% if console.rentals[0].approved? %>
                        <%= link_to console_rental_path(console, console.rentals[0]), class: "nes-badge is-icon", style: "height:100%;" do %>
                          <span class="is-error">Rented</span>
                        <% end %>
                      <% else %>
                        <%= link_to console_rental_path(console, console.rentals[0]), class: "nes-badge is-icon", style: "height:100%;" do %>
                          <span class="is-warning">Pending</span>
                        <% end %>
                      <% end %>
                    </div>
                  <% else %>
                    <h2 class="card-trip-pricing">£<%= console.price_per_day %> per day</h2>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="py-4 px-4">
        <div class="d-flex align-items-center justify-content-between mb-3">
          <h5 class="mb-0">My rentals</h5>
          <%= link_to 'Rent a console', consoles_path, class: "nes-btn is-primary" %>
        </div>
        <div class="cards">
          <% if @rentals.empty? %>
            <div>
              <h4>You're not renting any consoles ): Rent one now!</h4>
            </div>
          <% else %>
            <% @rentals.each do |rental| %>
              <div class="card-trip">
                <div class="profile-card-image-edit-button">
                  <%= link_to console_path(rental.console) do %>
                    <% if rental.console.photo.attached? %>
                      <%= cl_image_tag rental.console.photo.key, style:'object-fit:cover;'%>
                    <% else %>
                      <img src="https://res.cloudinary.com/xanldn89/image/upload/v1629884209/stock_console_lktnhq.jpg" />
                    <% end %>
                  <% end %>
                  <%# <%= link_to 'Edit', edit_console_path(console), class: "nes-btn is-warning edit-button", style: 'padding: 8px 4px;' %>
                </div>
                <div class="card-trip-infos">
                  <div class="card-name-and-info-text">
                    <h2><%= link_to rental.console.name, console_path(rental.console) %></h2>
                    <p><%= rental.console.description %></p>
                  </div>
                  <div class="card-badge">
                    <% if rental.approved? %>
                      <%= link_to console_rental_path(rental.console, rental), class: "nes-badge is-icon", style: "height:100%;" do %>
                        <span class="is-error">Rented</span>
                      <% end %>
                    <% else %>
                      <%= link_to console_rental_path(rental.console, rental), class: "nes-badge is-icon", style: "height:100%;" do %>
                        <span class="is-warning">Pending</span>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="row py-5 px-4">
  <div class="col-md-8 mx-auto">
    <div class="nes-container overflow-hidden">
      <div class="px-4 pt-0 pb-4 cover">
        <div class="media align-items-end profile-head">
          <div class="profile mr-3">
            <% if @user.photo.attached? %>
              <%= cl_image_tag @user.photo.key, style: 'width: 130px;', class:'rounded mb-2 img-thumbnail' %>
            <% else %>
              <img src="https://res.cloudinary.com/xanldn89/image/upload/c_thumb,w_200,g_face/v1630064327/stock_8_bit_hspodr.jpg" alt="..." width="130"
              class="rounded mb-2 img-thumbnail">
            <% end %>
          </div>
          <div class="media-body mb-5 text-white">
            <h4 class="mt-0 mb-0"><%= @user.first_name %></h4>
            <p class="small mb-4"> <i class="fas fa-map-marker-alt mr-2"></i><%= @user.address %></p>
          </div>
        </div>
      </div>
      <div class="bg-light p-4 d-flex justify-content-end text-center">
        <ul class="list-inline mb-0">
          <li class="list-inline-item">
            <%# <%  raise %>
            <h5 class="font-weight-bold mb-0 d-block"><%= @consoles.count %></h5><small class="text-muted"> <i
                class="fas fa-image mr-1"></i>Consoles</small>
          </li>
          <li class="list-inline-item">
            <h5 class="font-weight-bold mb-0 d-block" style="font-size:16px;">
              <%# @user.rating.times do %><% 5.times do %>
              👾
              <% end %>
            </h5><small class="text-muted"> <i class="fas fa-user mr-1"></i>Rating</small>
          </li>
        </ul>
      </div>
      <div class="px-4 py-3">
        <h5 class="mb-0">About</h5>
        <div class="p-4 rounded shadow-sm bg-light">
          <p class="font-italic mb-0"><%= @user.about %></p>
        </div>
      </div>
      <div class="py-4 px-4">
        <div class="d-flex align-items-center justify-content-between mb-3">
          <h5 class="mb-0">Consoles for rent</h5>
        </div>
        <div class="cards">
          <% if @consoles.empty? %>
            <div>
              <h4>This user does not have any consoles for rent</h4>
            </div>
          <% else %>
            <% @consoles.each do |console| %>
              <div class="card-trip">
                <div class="profile-card-image-edit-button">
                  <%= link_to console_path(console) do %>
                    <% if console.photo.attached? %>
                      <%= cl_image_tag console.photo.key, style:'object-fit:cover;'%>
                    <% else %>
                      <img src="https://res.cloudinary.com/xanldn89/image/upload/v1629884209/stock_console_lktnhq.jpg" />
                    <% end %>
                  <% end %>
                </div>
                <div class="card-trip-infos">
                  <div class="card-name-and-info-text">
                    <h2><%= link_to console.name, console_path(console) %></h2>
                    <p><%= console.description %></p>
                  </div>
                  <% if console.rentals[0] %>
                    <div class="card-badge">
                      <% if console.rentals[0].approved? %>
                        <%= link_to console_path(console), class: "nes-badge is-icon", style: "height:100%;" do %>
                          <span class="is-error">Rented</span>
                        <% end %>
                      <% else %>
                        <%= link_to console_path(console), class: "nes-badge is-icon", style: "height:100%;" do %>
                          <span class="is-warning">Pending</span>
                        <% end %>
                      <% end %>
                    </div>
                  <% else %>
                    <h2 class="card-trip-pricing">£<%= console.price_per_day %> per day</h2>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>