config/routes.rb
Rails.application.routes.draw do
  # get 'users/profile'
  # resources :users, only: %i[show new create destroy]
  root to: 'pages#home'
  devise_for :users
  get '/profile', to: 'users#profile', as: 'profile'
  get '/users/:id', to: 'users#show', as: 'user'
  resources :consoles do
    resources :rentals
    get '/rentals/:id/confirm', to: 'rentals#confirm', as: 'confirm_rental'
    get '/rentals/:id/approve', to: 'rentals#approve', as: 'approve_rental'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :console

  validates :start_rental_date, :end_rental_date, presence: true
  validate :date_logic

  def date_logic
    if Date.today > start_rental_date
      errors.add(:start_rental_date, "cannot be in the past")
    elsif Date.today > end_rental_date
      errors.add(:end_rental_date, "cannot be in the past")
    end

    errors.add(:end_rental_date, "cannot be before start date") if start_rental_date > end_rental_date
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :gets_console
  before_action :gets_owner, only: %i[new create edit update]
  before_action :gets_rental, only: %i[show confirm approve edit update destroy]

  def new
    @rental = Rental.new
  end

  def create
    @rental = Rental.new(start_rental_date: rental_params[:start_rental_date],
                         end_rental_date: rental_params[:end_rental_date],
                         console_id: @console.id,
                         user_id: @owner.id,
                         current_renter_id: current_user.id,
                         approved?: false)
    if @rental.save
      redirect_to console_rental_path(@console.id, @rental)
    else
      render :new
    end
  end

  def confirm
    @renter = User.find(@rental.current_renter_id)
  end

  def approve
    @rental.update(approved?: true)
    @rental.save
    redirect_to console_rental_path(@console, @rental)
  end

  def show
    @renter = User.find(@rental.current_renter_id)
    if current_user.id == @console.user_id && @rental.approved? == false
      redirect_to console_confirm_rental_path(@console, @rental)
    end
  end

  def edit; end

  def update
    @rental.update(start_rental_date: rental_params[:start_rental_date],
                   end_rental_date: rental_params[:end_rental_date])
    if @rental.save
      redirect_to console_rental_path(@console.id, @rental)
    else
      render :new
    end
  end

  def destroy
    @rental.delete
    redirect_to console_path(@console)
  end

  private

  def gets_console
    @console = Console.find(params[:console_id])
  end

  def gets_owner
    @owner = User.find(@console.user_id)
  end

  def gets_rental
    @rental = Rental.where("console_id = ?", @console.id)[0]
  end

  def rental_params
    params.require(:rental).permit(:current_rental_days, :start_rental_date, :end_rental_date)
  end
end

app/views/rentals/confirm.html.erb
<div class="container">
  <div class="nes-container is-rounded">
    <h1>Approve Rental</h1>

    <h2><%= @renter.first_name %> wants to rent <%= @console.name %>!</h2>

    <table>
      <tr>
        <td>
          <h3>Start rental date: </h3>
        </td>
        <td>
          <h3><%= @rental.start_rental_date %></h3>
        </td>
      </tr>
      <tr>
        <td>
          <h3>End rental date: </h3>
        </td>
        <td>
          <h3><%= @rental.end_rental_date %></h3>
        </td>
      </tr>
    </table>

    <h2>Total Income:</h2>
    <h3>$<%= (@console.price_per_day * (@rental.end_rental_date - @rental.start_rental_date)).to_i %></h3>

    <%= link_to 'Approve', console_approve_rental_path(@console, @rental), class: "nes-btn is-primary" %>
    <%= link_to 'Decline', console_rental_path(@console, @rental), class: "nes-btn is-error",
                                                                          method: :delete,
                                                                          data: {confirm: "Are you sure?"} %>
    <%= link_to 'Back', :back, class: "nes-btn is-secondary" %>
  </div>
</div>

app/views/rentals/edit.html.erb
<div class="container">
  <div class="nes-container is-rounded">
    <h1>Edit the rental for <%= @console.name %></h1>
    <p>from <%= @owner.first_name %> <%= @owner.last_name %></p>
    <h3>Rental price per day: $<%= @console.price_per_day %></h3>
    <h6>Minimum rental time: <%= @console.min_rental_time %> days</h6>
    <h6>Maximum rental time: <%= @console.max_rental_time %> days</h6>
    <h4>How long would you like to rent this console for? (Between <%= @console.min_rental_time %> and <%= @console.max_rental_time %> days) </h4>
    <%= simple_form_for [@console, @rental] do |f| %>
      <%= f.input :start_rental_date, as: :date, html5: true, input_html: { class: "nes-input", min: Date.today.to_s } %>
      <%= f.input :end_rental_date, as: :date, html5: true, input_html: { class: "nes-input",
                                                                          min: (Date.today + @console.min_rental_time).to_s,
                                                                          max: (Date.today + @console.max_rental_time).to_s } %>
      <%= f.submit class: "nes-btn is-primary" %>
      <%= link_to 'Cancel Rental', console_rental_path(@console, @rental), class: "nes-btn is-error",
                                                                          method: :delete,
                                                                          data: {confirm: "Are you sure?"} %>
      <%= link_to 'Back', :back, class: "nes-btn is-secondary" %>
    <% end %>
  </div>
</div>

app/views/rentals/new.html.erb
<div class="container">
  <div class="nes-container is-rounded">
    <h1>Rent the <%= @console.name %></h1>
    <p>from <%= @owner.first_name %> <%= @owner.last_name %></p>
    <h3>Rental price per day: $<%= @console.price_per_day %></h3>
    <h6>Minimum rental time: <%= @console.min_rental_time %> days</h6>
    <h6>Maximum rental time: <%= @console.max_rental_time %> days</h6>
    <h4>How long would you like to rent this console for? (Between <%= @console.min_rental_time %> and <%= @console.max_rental_time %> days) </h4>
    <%= simple_form_for [@console, @rental] do |f| %>
      <%= f.input :start_rental_date, as: :date, html5: true, input_html: { class: "nes-input", min: Date.today.to_s } %>
      <%= f.input :end_rental_date, as: :date, html5: true, input_html: { class: "nes-input",
                                                                          min: (Date.today + @console.min_rental_time).to_s,
                                                                          max: (Date.today + @console.max_rental_time).to_s } %>
      <%= f.submit class: "nes-btn is-primary" %>
      <%= link_to 'Back', :back, class: "nes-btn is-secondary" %>
    <% end %>
  </div>
</div>

app/views/rentals/show.html.erb
<% if current_user.id == @console.user_id %>

  <div class="container">
    <div class="nes-container is-rounded">
      <h1>Rental Confirmation</h1>

      <h2><%= @renter.first_name %> is renting <%= @console.name %>!</h2>

      <table>
        <tr>
          <td>
            <h3>Start rental date: </h3>
          </td>
          <td>
            <h3><%= @rental.start_rental_date %></h3>
          </td>
        </tr>
        <tr>
          <td>
            <h3>End rental date: </h3>
          </td>
          <td>
            <h3><%= @rental.end_rental_date %></h3>
          </td>
        </tr>
      </table>

      <h2>Total Income:</h2>
      <h3>$<%= (@console.price_per_day * (@rental.end_rental_date - @rental.start_rental_date)).to_i %></h3>

      <%= link_to 'Cancel Rental', console_rental_path(@console, @rental), class: "nes-btn is-error",
                                                                            method: :delete,
                                                                            data: {confirm: "Are you sure?"} %>
      <%= link_to 'Back', :back, class: "nes-btn is-secondary" %>
    </div>
  </div>

<% else %>

  <% if @rental.approved? %>
    <div class="container">
      <div class="nes-container is-rounded">
        <h1>Rental Confirmation</h1>

        <h2>You are renting <%= @console.name %>!</h2>

        <table>
          <tr>
            <td>
              <h3>Start rental date: </h3>
            </td>
            <td>
              <h3><%= @rental.start_rental_date %></h3>
            </td>
          </tr>
          <tr>
            <td>
              <h3>End rental date: </h3>
            </td>
            <td>
              <h3><%= @rental.end_rental_date %></h3>
            </td>
          </tr>
        </table>

        <h2>Total Cost:</h2>
        <h3>$<%= (@console.price_per_day * (@rental.end_rental_date - @rental.start_rental_date)).to_i %></h3>

        <%= link_to 'Edit', edit_console_rental_path(@console, @rental), class: "nes-btn is-warning" %>
        <%= link_to 'Cancel Rental', console_rental_path(@console, @rental), class: "nes-btn is-error",
                                                                              method: :delete,
                                                                              data: {confirm: "Are you sure?"} %>
        <%= link_to 'Back', :back, class: "nes-btn is-secondary" %>
      </div>
    </div>
  <% else %>
    <div class="container">
      <div class="nes-container is-rounded">
        <h1>Awaiting Confirmation</h1>

        <h2>You have requested to rent <%= @console.name %>!</h2>

        <table>
          <tr>
            <td>
              <h3>Start rental date: </h3>
            </td>
            <td>
              <h3><%= @rental.start_rental_date %></h3>
            </td>
          </tr>
          <tr>
            <td>
              <h3>End rental date: </h3>
            </td>
            <td>
              <h3><%= @rental.end_rental_date %></h3>
            </td>
          </tr>
        </table>

        <h2>Total to be paid:</h2>
        <h3>$<%= (@console.price_per_day * (@rental.end_rental_date - @rental.start_rental_date)).to_i %></h3>

        <%= link_to 'Edit', edit_console_rental_path(@console, @rental), class: "nes-btn is-warning" %>
        <%= link_to 'Cancel Rental', console_rental_path(@console, @rental), class: "nes-btn is-error",
                                                                              method: :delete,
                                                                              data: {confirm: "Are you sure?"} %>
        <%= link_to 'Back', :back, class: "nes-btn is-secondary" %>
      </div>
    </div>
  <% end %>
<% end %>